// oct-conf.h.in
/*

Copyright (C) 1996-2011 John W. Eaton

This file is part of Octave.

Octave is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 3 of the License, or (at your
option) any later version.

Octave is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with Octave; see the file COPYING.  If not, see
<http://www.gnu.org/licenses/>.

*/

#if !defined (octave_conf_h)
#define octave_conf_h 1

#ifndef OCTAVE_CONF_ALL_CFLAGS
#define OCTAVE_CONF_ALL_CFLAGS ""
#endif

#ifndef OCTAVE_CONF_ALL_CXXFLAGS
#define OCTAVE_CONF_ALL_CXXFLAGS ""
#endif

#ifndef OCTAVE_CONF_ALL_FFLAGS
#define OCTAVE_CONF_ALL_FFLAGS "-O"
#endif

#ifndef OCTAVE_CONF_ALL_LDFLAGS
#define OCTAVE_CONF_ALL_LDFLAGS ""
#endif

#ifndef OCTAVE_CONF_AMD_CPPFLAGS
#define OCTAVE_CONF_AMD_CPPFLAGS ""
#endif

#ifndef OCTAVE_CONF_AMD_LDFLAGS
#define OCTAVE_CONF_AMD_LDFLAGS ""
#endif

#ifndef OCTAVE_CONF_AMD_LIBS
#define OCTAVE_CONF_AMD_LIBS "-lamd"
#endif

#ifndef OCTAVE_CONF_ARFLAGS
#define OCTAVE_CONF_ARFLAGS "cru "
#endif

#ifndef OCTAVE_CONF_AR
#define OCTAVE_CONF_AR "ar"
#endif

#ifndef OCTAVE_CONF_BLAS_LIBS
#define OCTAVE_CONF_BLAS_LIBS "-lblas"
#endif

#ifndef OCTAVE_CONF_CAMD_CPPFLAGS
#define OCTAVE_CONF_CAMD_CPPFLAGS ""
#endif

#ifndef OCTAVE_CONF_CAMD_LDFLAGS
#define OCTAVE_CONF_CAMD_LDFLAGS ""
#endif

#ifndef OCTAVE_CONF_CAMD_LIBS
#define OCTAVE_CONF_CAMD_LIBS "-lcamd"
#endif

#ifndef OCTAVE_CONF_CARBON_LIBS
#define OCTAVE_CONF_CARBON_LIBS ""
#endif

#ifndef OCTAVE_CONF_CC
#define OCTAVE_CONF_CC "gcc"
#endif

#ifndef OCTAVE_CONF_CC_VERSION
#define OCTAVE_CONF_CC_VERSION "4.4.6 20120305 (Red Hat 4.4.6-4) (GCC) "
#endif

#ifndef OCTAVE_CONF_CCOLAMD_CPPFLAGS
#define OCTAVE_CONF_CCOLAMD_CPPFLAGS ""
#endif

#ifndef OCTAVE_CONF_CCOLAMD_LDFLAGS
#define OCTAVE_CONF_CCOLAMD_LDFLAGS ""
#endif

#ifndef OCTAVE_CONF_CCOLAMD_LIBS
#define OCTAVE_CONF_CCOLAMD_LIBS "-lccolamd"
#endif

#ifndef OCTAVE_CONF_CFLAGS
#define OCTAVE_CONF_CFLAGS "-g -O2 -pthread"
#endif

#ifndef OCTAVE_CONF_CHOLMOD_CPPFLAGS
#define OCTAVE_CONF_CHOLMOD_CPPFLAGS ""
#endif

#ifndef OCTAVE_CONF_CHOLMOD_LDFLAGS
#define OCTAVE_CONF_CHOLMOD_LDFLAGS ""
#endif

#ifndef OCTAVE_CONF_CHOLMOD_LIBS
#define OCTAVE_CONF_CHOLMOD_LIBS ""
#endif

#ifndef OCTAVE_CONF_COLAMD_CPPFLAGS
#define OCTAVE_CONF_COLAMD_CPPFLAGS ""
#endif

#ifndef OCTAVE_CONF_COLAMD_LDFLAGS
#define OCTAVE_CONF_COLAMD_LDFLAGS ""
#endif

#ifndef OCTAVE_CONF_COLAMD_LIBS
#define OCTAVE_CONF_COLAMD_LIBS "-lcolamd"
#endif

#ifndef OCTAVE_CONF_CPICFLAG
#define OCTAVE_CONF_CPICFLAG "-fPIC"
#endif

#ifndef OCTAVE_CONF_CPPFLAGS
#define OCTAVE_CONF_CPPFLAGS "-I/mnt/oqtansTools/oqtans_dep/include"
#endif

#ifndef OCTAVE_CONF_CURL_CPPFLAGS
#define OCTAVE_CONF_CURL_CPPFLAGS ""
#endif

#ifndef OCTAVE_CONF_CURL_LDFLAGS
#define OCTAVE_CONF_CURL_LDFLAGS ""
#endif

#ifndef OCTAVE_CONF_CURL_LIBS
#define OCTAVE_CONF_CURL_LIBS ""
#endif

#ifndef OCTAVE_CONF_CXSPARSE_CPPFLAGS
#define OCTAVE_CONF_CXSPARSE_CPPFLAGS ""
#endif

#ifndef OCTAVE_CONF_CXSPARSE_LDFLAGS
#define OCTAVE_CONF_CXSPARSE_LDFLAGS ""
#endif

#ifndef OCTAVE_CONF_CXSPARSE_LIBS
#define OCTAVE_CONF_CXSPARSE_LIBS "-lcxsparse"
#endif

#ifndef OCTAVE_CONF_CXXCPP
#define OCTAVE_CONF_CXXCPP "g++ -E"
#endif

#ifndef OCTAVE_CONF_CXXFLAGS
#define OCTAVE_CONF_CXXFLAGS "-g -O2"
#endif

#ifndef OCTAVE_CONF_CXXPICFLAG
#define OCTAVE_CONF_CXXPICFLAG "-fPIC"
#endif

#ifndef OCTAVE_CONF_CXX
#define OCTAVE_CONF_CXX "g++"
#endif

#ifndef OCTAVE_CONF_CXX_VERSION
#define OCTAVE_CONF_CXX_VERSION "4.4.6"
#endif

#ifndef OCTAVE_CONF_DEFAULT_PAGER
#define OCTAVE_CONF_DEFAULT_PAGER "less"
#endif

#ifndef OCTAVE_CONF_DEFS
#define OCTAVE_CONF_DEFS "-DPACKAGE_NAME=\"GNU Octave\" -DPACKAGE_TARNAME=\"octave\" -DPACKAGE_VERSION=\"3.4.3\" -DPACKAGE_STRING=\"GNU Octave 3.4.3\" -DPACKAGE_BUGREPORT=\"http://octave.org/bugs.html\" -DPACKAGE_URL=\"http://www.gnu.org/software/octave/\" -DPACKAGE=\"octave\" -DVERSION=\"3.4.3\" -DOCTAVE_SOURCE=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_DARWIN_C_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DSEPCHAR=':' -DSEPCHAR_STR=\":\" -DSIZEOF_VOID_P=8 -DSIZEOF_INT=4 -DSIZEOF_LONG=8 -DIDX_TYPE_LONG=1 -DOCTAVE_IDX_TYPE=long -DUSE_64_BIT_IDX_T=1 -D__NO_MATH_INLINES=1 -DCXX_NEW_FRIEND_TEMPLATE_DECL=1 -DCXX_ISO_COMPLIANT_LIBRARY=1 -DHAVE_FSEEKO=1 -DHAVE_ALLOCA_H=1 -DHAVE_ALLOCA=1 -DHAVE_CANONICALIZE_FILE_NAME=1 -DHAVE_GETCWD=1 -DHAVE_READLINK=1 -DHAVE_REALPATH=1 -DHAVE_CHOWN=1 -DHAVE_FCHOWN=1 -DHAVE_FCHDIR=1 -DHAVE_FCNTL=1 -DHAVE_SYMLINK=1 -DHAVE_FDOPENDIR=1 -DHAVE_MEMPCPY=1 -DHAVE_BTOWC=1 -DHAVE_ISBLANK=1 -DHAVE_ISWCTYPE=1 -DHAVE_MBSRTOWCS=1 -DHAVE_WMEMCHR=1 -DHAVE_WMEMCPY=1 -DHAVE_WMEMPCPY=1 -DHAVE___FPURGE=1 -DHAVE___FREADING=1 -DHAVE_GETDTABLESIZE=1 -DHAVE_GETLOGIN_R=1 -DHAVE_GETTIMEOFDAY=1 -DHAVE_FSTATAT=1 -DHAVE_GETPWNAM_R=1 -DHAVE_LINK=1 -DHAVE_LSTAT=1 -DHAVE_MBSINIT=1 -DHAVE_MBRTOWC=1 -DHAVE_MPROTECT=1 -DHAVE_MKFIFO=1 -DHAVE_MKSTEMP=1 -DHAVE_ALARM=1 -DHAVE_FCHMODAT=1 -DHAVE_MKDIRAT=1 -DHAVE_OPENAT=1 -DHAVE_UNLINKAT=1 -DHAVE_SIGACTION=1 -DHAVE_SIGALTSTACK=1 -DHAVE_SIGINTERRUPT=1 -DHAVE_SLEEP=1 -DHAVE_STRDUP=1 -DHAVE_TZSET=1 -DHAVE_STRPTIME=1 -DHAVE_LOCALTIME_R=1 -DHAVE_TIMES=1 -DHAVE_PIPE=1 -DHAVE_SNPRINTF=1 -DHAVE_ISWCNTRL=1 -DFUNC_REALPATH_WORKS=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SYS_SOCKET_H=1 -DHAVE_DIRENT_H=1 -DHAVE_WCTYPE_H=1 -DHAVE_NETDB_H=1 -DHAVE_GETOPT_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_SYS_CDEFS_H=1 -DHAVE_MATH_H=1 -DHAVE_SYS_MMAN_H=1 -DHAVE_SYS_SELECT_H=1 -DHAVE_WCHAR_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TIMES_H=1 -DHAVE_SYS_UIO_H=1 -DHAVE_FEATURES_H=1 -DHAVE_UNISTD_H=1 -DHAVE_CHOWN=1 -DHAVE_DECL_STRERROR_R=1 -DHAVE_STRERROR_R=1 -DSTRERROR_R_CHAR_P=1 -DHAVE_DECL_FCHDIR=1 -DHAVE_WORKING_O_NOATIME=1 -DHAVE_WORKING_O_NOFOLLOW=1 -DHAVE_DECL_STRMODE=0 -DHAVE_MBSTATE_T=1 -DHAVE_DECL_FSEEKO=1 -DHAVE_DECL_FTELLO=1 -DHAVE_DECL_GETCWD=1 -DHAVE_DECL_GETLOGIN_R=1 -DHAVE_DECL_GETLOGIN=1 -DHAVE_GETOPT_H=1 -DHAVE_GETOPT_LONG_ONLY=1 -D__GETOPT_PREFIX=rpl_ -DHAVE_DECL_GETENV=1 -Drestrict=__restrict -DHAVE_RAW_DECL_GETTIMEOFDAY=1 -DHAVE_LANGINFO_CODESET=1 -DHAVE_DECL_GETC_UNLOCKED=1 -DLSTAT_FOLLOWS_SLASHED_SYMLINK=1 -DHAVE_STDLIB_H=1 -DMALLOC_0_IS_NONNULL=1 -DHAVE_UNSIGNED_LONG_LONG_INT=1 -DHAVE_LONG_LONG_INT=1 -DHAVE_MAP_ANONYMOUS=1 -DHAVE_DECL_MEMRCHR=1 -DHAVE_RAW_DECL_PSELECT=1 -DHAVE_RAW_DECL_SELECT=1 -DPROMOTED_MODE_T=mode_t -DHAVE_SIGSET_T=1 -DHAVE__BOOL=1 -DHAVE_WCHAR_T=1 -DHAVE_DECL_STRDUP=1 -DHAVE_STRUCT_TM_TM_ZONE=1 -DHAVE_TM_ZONE=1 -DHAVE_TM_GMTOFF=1 -DHAVE_RAW_DECL_FFSL=1 -DHAVE_RAW_DECL_FFSLL=1 -DHAVE_RAW_DECL_MEMMEM=1 -DHAVE_RAW_DECL_MEMPCPY=1 -DHAVE_RAW_DECL_MEMRCHR=1 -DHAVE_RAW_DECL_RAWMEMCHR=1 -DHAVE_RAW_DECL_STPCPY=1 -DHAVE_RAW_DECL_STPNCPY=1 -DHAVE_RAW_DECL_STRCHRNUL=1 -DHAVE_RAW_DECL_STRDUP=1 -DHAVE_RAW_DECL_STRNCAT=1 -DHAVE_RAW_DECL_STRNDUP=1 -DHAVE_RAW_DECL_STRNLEN=1 -DHAVE_RAW_DECL_STRPBRK=1 -DHAVE_RAW_DECL_STRSEP=1 -DHAVE_RAW_DECL_STRCASESTR=1 -DHAVE_RAW_DECL_STRTOK_R=1 -DHAVE_RAW_DECL_STRERROR_R=1 -DHAVE_RAW_DECL_STRSIGNAL=1 -DHAVE_RAW_DECL_STRVERSCMP=1 -DHAVE_RAW_DECL_FFS=1 -DHAVE_RAW_DECL_STRCASECMP=1 -DHAVE_RAW_DECL_STRNCASECMP=1 -DHAVE_DECL_LOCALTIME_R=0 -DHAVE_WINT_T=1 -DHAVE_INTTYPES_H_WITH_UINTMAX=1 -DHAVE_STDINT_H_WITH_UINTMAX=1 -DHAVE_INTMAX_T=1 -DHAVE_SNPRINTF=1 -DHAVE_STRNLEN=1 -DHAVE_WCSLEN=1 -DHAVE_WCSNLEN=1 -DHAVE_MBRTOWC=1 -DHAVE_WCRTOMB=1 -DHAVE_DECL__SNPRINTF=0 -DHAVE_SNPRINTF_RETVAL_C99=1 -DHAVE_DECL_VSNPRINTF=1 -DHAVE_ALLOCA=1 -DGNULIB_CANONICALIZE_LGPL=1 -DGNULIB_TEST_CANONICALIZE_FILE_NAME=1 -DGNULIB_TEST_REALPATH=1 -DGNULIB_TEST_CHDIR=1 -DGNULIB_TEST_CHOWN=1 -DGNULIB_TEST_CLOEXEC=1 -DGNULIB_TEST_CLOSE=1 -DHAVE_CLOSEDIR=1 -DGNULIB_TEST_CLOSEDIR=1 -DD_INO_IN_DIRENT=1 -DHAVE_STRUCT_DIRENT_D_TYPE=1 -DHAVE_RAW_DECL_ALPHASORT=1 -DHAVE_RAW_DECL_CLOSEDIR=1 -DHAVE_RAW_DECL_DIRFD=1 -DHAVE_RAW_DECL_FDOPENDIR=1 -DHAVE_RAW_DECL_OPENDIR=1 -DHAVE_RAW_DECL_READDIR=1 -DHAVE_RAW_DECL_REWINDDIR=1 -DHAVE_RAW_DECL_SCANDIR=1 -DHAVE_DIRFD=1 -DHAVE_DECL_DIRFD=1 -DGNULIB_TEST_DIRFD=1 -DGNULIB_TEST_DUP=1 -DHAVE_DUP2=1 -DGNULIB_TEST_DUP2=1 -DGNULIB_TEST_FCHDIR=1 -DGNULIB_TEST_FCLOSE=1 -DGNULIB_TEST_FCNTL=1 -DHAVE_RAW_DECL_FCNTL=1 -DHAVE_RAW_DECL_OPENAT=1 -DHAVE_DECL_FDOPENDIR=1 -DGNULIB_TEST_FDOPENDIR=1 -DGNULIB_FDOPENDIR=1 -DGNULIB_FFLUSH=1 -DGNULIB_TEST_FFLUSH=1 -DGNULIB_TEST_FLOOR=1 -Dfnmatch=posix_fnmatch -DHAVE_DECL_ISBLANK=1 -DGNULIB_TEST_FOPEN=1 -DHAVE_DECL_FPURGE=0 -DGNULIB_TEST_FPURGE=1 -DGNULIB_TEST_FSEEK=1 -DGNULIB_TEST_FSEEKO=1 -DGNULIB_TEST_FSTAT=1 -DGNULIB_TEST_FTELL=1 -DGNULIB_TEST_FTELLO=1 -DHAVE_PARTLY_WORKING_GETCWD=1 -DHAVE_GETPAGESIZE=1 -DGNULIB_GETCWD=1 -DGNULIB_TEST_GETCWD=1 -DGNULIB_TEST_GETCWD=1 -DGNULIB_TEST_GETDTABLESIZE=1 -DHAVE_GETHOSTNAME=1 -DGNULIB_TEST_GETHOSTNAME=1 -DGNULIB_TEST_GETLOGIN_R=1 -DGNULIB_TEST_GETOPT_GNU=1 -D__GETOPT_PREFIX=rpl_ -DGETTIMEOFDAY_TIMEZONE=struct timezone -DGNULIB_TEST_GETTIMEOFDAY=1 -DHAVE_GLOB_H=1 -DHAVE_LCHOWN=1 -DGNULIB_TEST_LCHOWN=1 -DGNULIB_TEST_LINK=1 -DGNULIB_TEST_LSEEK=1 -DGNULIB_TEST_LSTAT=1 -DHAVE_MALLOC_POSIX=1 -DGNULIB_TEST_MALLOC_POSIX=1 -DHAVE_RAW_DECL_ACOSL=1 -DHAVE_RAW_DECL_ASINL=1 -DHAVE_RAW_DECL_ATANL=1 -DHAVE_RAW_DECL_CEILF=1 -DHAVE_RAW_DECL_CEILL=1 -DHAVE_RAW_DECL_COSL=1 -DHAVE_RAW_DECL_EXPL=1 -DHAVE_RAW_DECL_FLOORF=1 -DHAVE_RAW_DECL_FLOORL=1 -DHAVE_RAW_DECL_FREXPL=1 -DHAVE_RAW_DECL_LDEXPL=1 -DHAVE_RAW_DECL_LOGB=1 -DHAVE_RAW_DECL_LOGL=1 -DHAVE_RAW_DECL_ROUND=1 -DHAVE_RAW_DECL_ROUNDF=1 -DHAVE_RAW_DECL_ROUNDL=1 -DHAVE_RAW_DECL_SINL=1 -DHAVE_RAW_DECL_SQRTL=1 -DHAVE_RAW_DECL_TANL=1 -DHAVE_RAW_DECL_TRUNC=1 -DHAVE_RAW_DECL_TRUNCF=1 -DHAVE_RAW_DECL_TRUNCL=1 -DGNULIB_TEST_MBRTOWC=1 -DGNULIB_TEST_MBSINIT=1 -DGNULIB_TEST_MBSRTOWCS=1 -DGNULIB_TEST_MEMCHR=1 -DHAVE_MEMPCPY=1 -DGNULIB_TEST_MEMPCPY=1 -DHAVE_MEMRCHR=1 -DGNULIB_TEST_MEMRCHR=1 -DGNULIB_TEST_MKFIFO=1 -DGNULIB_TEST_MKSTEMP=1 -DGNULIB_TEST_MKTIME=1 -DHAVE_BUG_BIG_NANOSLEEP=1 -DGNULIB_TEST_NANOSLEEP=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_SYS_SYSCTL_H=1 -DHAVE_SCHED_GETAFFINITY=1 -DHAVE_SYSCTL=1 -DHAVE_SCHED_GETAFFINITY_LIKE_GLIBC=1 -DGNULIB_TEST_OPEN=1 -DGNULIB_OPENAT=1 -DHAVE_OPENDIR=1 -DGNULIB_TEST_OPENDIR=1 -DHAVE_DECL_PROGRAM_INVOCATION_NAME=1 -DHAVE_DECL_PROGRAM_INVOCATION_SHORT_NAME=1 -DHAVE_RAISE=1 -DGNULIB_TEST_RAISE=1 -DHAVE_READDIR=1 -DGNULIB_TEST_READDIR=1 -DGNULIB_TEST_READLINK=1 -DHAVE_REALLOC_POSIX=1 -DGNULIB_TEST_REALLOC_POSIX=1 -DGNULIB_TEST_RENAME=1 -DGNULIB_TEST_RMDIR=1 -DHAVE_DECL_ROUND=1 -DGNULIB_TEST_ROUND=1 -DHAVE_DECL_ROUNDF=1 -DGNULIB_TEST_ROUNDF=1 -DGNULIB_TEST_SELECT=1 -DHAVE_STRUCT_SIGACTION_SA_SIGACTION=1 -DGNULIB_TEST_SIGACTION=1 -DHAVE_RAW_DECL_PTHREAD_SIGMASK=1 -DHAVE_RAW_DECL_SIGACTION=1 -DHAVE_RAW_DECL_SIGADDSET=1 -DHAVE_RAW_DECL_SIGDELSET=1 -DHAVE_RAW_DECL_SIGEMPTYSET=1 -DHAVE_RAW_DECL_SIGFILLSET=1 -DHAVE_RAW_DECL_SIGISMEMBER=1 -DHAVE_RAW_DECL_SIGPENDING=1 -DHAVE_RAW_DECL_SIGPROCMASK=1 -DGNULIB_TEST_SIGPROCMASK=1 -DHAVE_STDINT_H=1 -DHAVE_DECL_SLEEP=1 -DGNULIB_TEST_SLEEP=1 -DGNULIB_TEST_STAT=1 -DHAVE_RAW_DECL_DPRINTF=1 -DHAVE_RAW_DECL_FSEEKO=1 -DHAVE_RAW_DECL_FTELLO=1 -DHAVE_RAW_DECL_GETDELIM=1 -DHAVE_RAW_DECL_GETLINE=1 -DHAVE_RAW_DECL_PCLOSE=1 -DHAVE_RAW_DECL_POPEN=1 -DHAVE_RAW_DECL_RENAMEAT=1 -DHAVE_RAW_DECL_SNPRINTF=1 -DHAVE_RAW_DECL_TMPFILE=1 -DHAVE_RAW_DECL_VDPRINTF=1 -DHAVE_RAW_DECL_VSNPRINTF=1 -DHAVE_RAW_DECL__EXIT=1 -DHAVE_RAW_DECL_ATOLL=1 -DHAVE_RAW_DECL_CANONICALIZE_FILE_NAME=1 -DHAVE_RAW_DECL_GETLOADAVG=1 -DHAVE_RAW_DECL_GETSUBOPT=1 -DHAVE_RAW_DECL_GRANTPT=1 -DHAVE_RAW_DECL_MKDTEMP=1 -DHAVE_RAW_DECL_MKOSTEMP=1 -DHAVE_RAW_DECL_MKOSTEMPS=1 -DHAVE_RAW_DECL_MKSTEMP=1 -DHAVE_RAW_DECL_MKSTEMPS=1 -DHAVE_RAW_DECL_PTSNAME=1 -DHAVE_RAW_DECL_RANDOM_R=1 -DHAVE_RAW_DECL_SRANDOM_R=1 -DHAVE_RAW_DECL_SETSTATE_R=1 -DHAVE_RAW_DECL_REALPATH=1 -DHAVE_RAW_DECL_RPMATCH=1 -DHAVE_RAW_DECL_SETENV=1 -DHAVE_RAW_DECL_STRTOD=1 -DHAVE_RAW_DECL_STRTOLL=1 -DHAVE_RAW_DECL_STRTOULL=1 -DHAVE_RAW_DECL_UNLOCKPT=1 -DHAVE_RAW_DECL_UNSETENV=1 -DHAVE_STRCASECMP=1 -DHAVE_STRNCASECMP=1 -DHAVE_DECL_STRNCASECMP=1 -DGNULIB_TEST_STRDUP=1 -DGNULIB_STRERROR=1 -DGNULIB_TEST_STRERROR=1 -Dmy_strftime=nstrftime -DGNULIB_TEST_STRPTIME=1 -DGNULIB_TEST_SYMLINK=1 -DHAVE_RAW_DECL_PSELECT=1 -DHAVE_RAW_DECL_SELECT=1 -DHAVE_SHUTDOWN=1 -DHAVE_STRUCT_SOCKADDR_STORAGE=1 -DHAVE_SA_FAMILY_T=1 -DHAVE_STRUCT_SOCKADDR_STORAGE_SS_FAMILY=1 -DHAVE_RAW_DECL_SOCKET=1 -DHAVE_RAW_DECL_CONNECT=1 -DHAVE_RAW_DECL_ACCEPT=1 -DHAVE_RAW_DECL_BIND=1 -DHAVE_RAW_DECL_GETPEERNAME=1 -DHAVE_RAW_DECL_GETSOCKNAME=1 -DHAVE_RAW_DECL_GETSOCKOPT=1 -DHAVE_RAW_DECL_LISTEN=1 -DHAVE_RAW_DECL_RECV=1 -DHAVE_RAW_DECL_SEND=1 -DHAVE_RAW_DECL_RECVFROM=1 -DHAVE_RAW_DECL_SENDTO=1 -DHAVE_RAW_DECL_SETSOCKOPT=1 -DHAVE_RAW_DECL_SHUTDOWN=1 -DHAVE_RAW_DECL_ACCEPT4=1 -DHAVE_RAW_DECL_FCHMODAT=1 -DHAVE_RAW_DECL_FSTAT=1 -DHAVE_RAW_DECL_FSTATAT=1 -DHAVE_RAW_DECL_FUTIMENS=1 -DHAVE_RAW_DECL_LCHMOD=1 -DHAVE_RAW_DECL_LSTAT=1 -DHAVE_RAW_DECL_MKDIRAT=1 -DHAVE_RAW_DECL_MKFIFO=1 -DHAVE_RAW_DECL_MKFIFOAT=1 -DHAVE_RAW_DECL_MKNOD=1 -DHAVE_RAW_DECL_MKNODAT=1 -DHAVE_RAW_DECL_STAT=1 -DHAVE_RAW_DECL_UTIMENSAT=1 -DHAVE_STRUCT_TMS=1 -DHAVE_RAW_DECL_TIMES=1 -DGNULIB_TEST_TIME_R=1 -DHAVE___SECURE_GETENV=1 -DGNULIB_TEST_TMPFILE=1 -DHAVE_DECL_TRUNC=1 -DGNULIB_TEST_TRUNC=1 -DHAVE_DECL_TRUNCF=1 -DGNULIB_TEST_TRUNCF=1 -DHAVE_RAW_DECL_CHDIR=1 -DHAVE_RAW_DECL_CHOWN=1 -DHAVE_RAW_DECL_DUP=1 -DHAVE_RAW_DECL_DUP2=1 -DHAVE_RAW_DECL_DUP3=1 -DHAVE_RAW_DECL_ENVIRON=1 -DHAVE_RAW_DECL_EUIDACCESS=1 -DHAVE_RAW_DECL_FACCESSAT=1 -DHAVE_RAW_DECL_FCHDIR=1 -DHAVE_RAW_DECL_FCHOWNAT=1 -DHAVE_RAW_DECL_FDATASYNC=1 -DHAVE_RAW_DECL_FSYNC=1 -DHAVE_RAW_DECL_FTRUNCATE=1 -DHAVE_RAW_DECL_GETCWD=1 -DHAVE_RAW_DECL_GETDOMAINNAME=1 -DHAVE_RAW_DECL_GETDTABLESIZE=1 -DHAVE_RAW_DECL_GETGROUPS=1 -DHAVE_RAW_DECL_GETHOSTNAME=1 -DHAVE_RAW_DECL_GETLOGIN=1 -DHAVE_RAW_DECL_GETLOGIN_R=1 -DHAVE_RAW_DECL_GETPAGESIZE=1 -DHAVE_RAW_DECL_GETUSERSHELL=1 -DHAVE_RAW_DECL_SETUSERSHELL=1 -DHAVE_RAW_DECL_ENDUSERSHELL=1 -DHAVE_RAW_DECL_GROUP_MEMBER=1 -DHAVE_RAW_DECL_LCHOWN=1 -DHAVE_RAW_DECL_LINK=1 -DHAVE_RAW_DECL_LINKAT=1 -DHAVE_RAW_DECL_LSEEK=1 -DHAVE_RAW_DECL_PIPE=1 -DHAVE_RAW_DECL_PIPE2=1 -DHAVE_RAW_DECL_PREAD=1 -DHAVE_RAW_DECL_PWRITE=1 -DHAVE_RAW_DECL_READLINK=1 -DHAVE_RAW_DECL_READLINKAT=1 -DHAVE_RAW_DECL_RMDIR=1 -DHAVE_RAW_DECL_SLEEP=1 -DHAVE_RAW_DECL_SYMLINK=1 -DHAVE_RAW_DECL_SYMLINKAT=1 -DHAVE_RAW_DECL_TTYNAME_R=1 -DHAVE_RAW_DECL_UNLINK=1 -DHAVE_RAW_DECL_UNLINKAT=1 -DHAVE_RAW_DECL_USLEEP=1 -DGNULIB_TEST_UNLINK=1 -DHAVE_VSNPRINTF=1 -DGNULIB_TEST_VSNPRINTF=1 -DHAVE_RAW_DECL_BTOWC=1 -DHAVE_RAW_DECL_WCTOB=1 -DHAVE_RAW_DECL_MBSINIT=1 -DHAVE_RAW_DECL_MBRTOWC=1 -DHAVE_RAW_DECL_MBRLEN=1 -DHAVE_RAW_DECL_MBSRTOWCS=1 -DHAVE_RAW_DECL_MBSNRTOWCS=1 -DHAVE_RAW_DECL_WCRTOMB=1 -DHAVE_RAW_DECL_WCSRTOMBS=1 -DHAVE_RAW_DECL_WCSNRTOMBS=1 -DHAVE_RAW_DECL_WCWIDTH=1 -DHAVE_RAW_DECL_WMEMCHR=1 -DHAVE_RAW_DECL_WMEMCMP=1 -DHAVE_RAW_DECL_WMEMCPY=1 -DHAVE_RAW_DECL_WMEMMOVE=1 -DHAVE_RAW_DECL_WMEMSET=1 -DHAVE_RAW_DECL_WCSLEN=1 -DHAVE_RAW_DECL_WCSNLEN=1 -DHAVE_RAW_DECL_WCSCPY=1 -DHAVE_RAW_DECL_WCPCPY=1 -DHAVE_RAW_DECL_WCSNCPY=1 -DHAVE_RAW_DECL_WCPNCPY=1 -DHAVE_RAW_DECL_WCSCAT=1 -DHAVE_RAW_DECL_WCSNCAT=1 -DHAVE_RAW_DECL_WCSCMP=1 -DHAVE_RAW_DECL_WCSNCMP=1 -DHAVE_RAW_DECL_WCSCASECMP=1 -DHAVE_RAW_DECL_WCSNCASECMP=1 -DHAVE_RAW_DECL_WCSCOLL=1 -DHAVE_RAW_DECL_WCSXFRM=1 -DHAVE_RAW_DECL_WCSDUP=1 -DHAVE_RAW_DECL_WCSCHR=1 -DHAVE_RAW_DECL_WCSRCHR=1 -DHAVE_RAW_DECL_WCSCSPN=1 -DHAVE_RAW_DECL_WCSSPN=1 -DHAVE_RAW_DECL_WCSPBRK=1 -DHAVE_RAW_DECL_WCSSTR=1 -DHAVE_RAW_DECL_WCSTOK=1 -DHAVE_RAW_DECL_WCSWIDTH=1 -DHAVE_TOWLOWER=1 -DHAVE_RAW_DECL_WCTYPE=1 -DHAVE_RAW_DECL_ISWCTYPE=1 -DHAVE_RAW_DECL_WCTRANS=1 -DHAVE_RAW_DECL_TOWCTRANS=1 -DHAVE_STDINT_H=1 -DHAVE_PTHREAD=1 -DFLOAT_TRUNCATE= -DHAVE_LIBM=1 -DF77_FUNC(name,NAME)=name ## _ -DF77_FUNC_(name,NAME)=name ## _ -DHAVE_IEEE754_DATA_FORMAT=1 -DHAVE_CXX_COMPLEX_SETTERS=1 -DHAVE_CXX_COMPLEX_REFERENCE_ACCESSORS=1 -DHAVE_PCRE_COMPILE=1 -DHAVE_ZLIB_H=1 -DHAVE_Z=1 -DHAVE_GLPK_H=1 -DHAVE_GLPK=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_QRUPDATE=1 -DHAVE_QRUPDATE_LUU=1 -DHAVE_SUITESPARSE_AMD_H=1 -DHAVE_AMD=1 -DHAVE_SUITESPARSE_CAMD_H=1 -DHAVE_CAMD=1 -DHAVE_SUITESPARSE_COLAMD_H=1 -DHAVE_COLAMD=1 -DHAVE_SUITESPARSE_CCOLAMD_H=1 -DHAVE_CCOLAMD=1 -DHAVE_SUITESPARSE_CHOLMOD_H=1 -DHAVE_SUITESPARSE_CS_H=1 -DHAVE_CXSPARSE=1 -DHAVE_GETPWNAM=1 -DHAVE_DEV_T=1 -DHAVE_INO_T=1 -DHAVE_LONG_LONG_INT=1 -DHAVE_UNSIGNED_LONG_LONG_INT=1 -DSIZEOF_SHORT=2 -DSIZEOF_INT=4 -DSIZEOF_LONG=8 -DSIZEOF_LONG_LONG=8 -DHAVE_ALLOCA_H=1 -DHAVE_ALLOCA=1 -DHAVE_PLACEMENT_DELETE=1 -DHAVE_DYNAMIC_AUTO_ARRAYS=1 -DHAVE_FAST_INT_OPS=1 -DSIZEOF_LONG_DOUBLE=16 -DHAVE_DIRENT_H=1 -DHAVE_SYS_WAIT_H=1 -DHAVE_CURSES_H=1 -DHAVE_DLFCN_H=1 -DHAVE_GRP_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_LOCALE_H=1 -DHAVE_MEMORY_H=1 -DHAVE_NCURSES_H=1 -DHAVE_POLL_H=1 -DHAVE_PTHREAD_H=1 -DHAVE_PWD_H=1 -DHAVE_SYS_IOCTL_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_SYS_POLL_H=1 -DHAVE_SYS_RESOURCE_H=1 -DHAVE_SYS_SELECT_H=1 -DHAVE_SYS_UTSNAME_H=1 -DHAVE_TERMCAP_H=1 -DHAVE_SSTREAM=1 -DHAVE_TERMIOS_H=1 -DHAVE_TERMIO_H=1 -DHAVE_SGTTY_H=1 -DHAVE_FNMATCH_H=1 -DHAVE_BASENAME=1 -DHAVE_CANONICALIZE_FILE_NAME=1 -DHAVE_CHMOD=1 -DHAVE_DUP2=1 -DHAVE_ENDGRENT=1 -DHAVE_ENDPWENT=1 -DHAVE_EXECVP=1 -DHAVE_EXPM1=1 -DHAVE_EXPM1F=1 -DHAVE_FORK=1 -DHAVE_GETEGID=1 -DHAVE_GETEUID=1 -DHAVE_GETGID=1 -DHAVE_GETGRENT=1 -DHAVE_GETGRGID=1 -DHAVE_GETGRNAM=1 -DHAVE_GETPGRP=1 -DHAVE_GETPID=1 -DHAVE_GETPPID=1 -DHAVE_GETPWENT=1 -DHAVE_GETPWUID=1 -DHAVE_GETUID=1 -DHAVE_GETWD=1 -DHAVE_KILL=1 -DHAVE_LGAMMA=1 -DHAVE_LGAMMAF=1 -DHAVE_LGAMMA_R=1 -DHAVE_LGAMMAF_R=1 -DHAVE_LOCALTIME_R=1 -DHAVE_LOG1P=1 -DHAVE_LOG1PF=1 -DHAVE_MKSTEMP=1 -DHAVE_PIPE=1 -DHAVE_PUTENV=1 -DHAVE_REALPATH=1 -DHAVE_RINDEX=1 -DHAVE_ROUNDL=1 -DHAVE_SELECT=1 -DHAVE_SETGRENT=1 -DHAVE_SETLOCALE=1 -DHAVE_SETPWENT=1 -DHAVE_SETVBUF=1 -DHAVE_SIGLONGJMP=1 -DHAVE_STRSIGNAL=1 -DHAVE_TEMPNAM=1 -DHAVE_TGAMMAF=1 -DHAVE_UMASK=1 -DHAVE_UNAME=1 -DHAVE_UTIME=1 -DHAVE_WAITPID=1 -DHAVE_DECL_EXP2=1 -DHAVE_DECL_ROUND=1 -DHAVE_DECL_TGAMMA=1 -DHAVE_EXP2=1 -DHAVE_ROUND=1 -DHAVE_TGAMMA=1 -DHAVE_DLOPEN_API=1 -DENABLE_DYNAMIC_LINKING=1 -DHAVE_CMATH_ISNAN=1 -DHAVE_CMATH_ISNANF=1 -DHAVE_CMATH_ISINF=1 -DHAVE_CMATH_ISINFF=1 -DHAVE_CMATH_ISFINITE=1 -DHAVE_CMATH_ISFINITEF=1 -DHAVE_FINITE=1 -DHAVE_ISNAN=1 -DHAVE_ISINF=1 -DHAVE_DECL_SIGNBIT=1 -DHAVE_ACOSH=1 -DHAVE_ACOSHF=1 -DHAVE_ASINH=1 -DHAVE_ASINHF=1 -DHAVE_ATANH=1 -DHAVE_ATANHF=1 -DHAVE_ERF=1 -DHAVE_ERFF=1 -DHAVE_ERFC=1 -DHAVE_ERFCF=1 -DHAVE_EXP2F=1 -DHAVE_LOG2=1 -DHAVE_LOG2F=1 -DHAVE_HYPOTF=1 -DHAVE_CBRT=1 -DHAVE_CBRTF=1 -DHAVE_STRUCT_STAT_ST_BLKSIZE=1 -DHAVE_STRUCT_STAT_ST_BLOCKS=1 -DHAVE_STRUCT_STAT_ST_RDEV=1 -DHAVE_STRUCT_TM_TM_ZONE=1 -DHAVE_TM_ZONE=1 -DEXCEPTION_IN_MATH=1 -DHAVE_DECL_SYS_SIGLIST=1 -DHAVE_GETRUSAGE=1 -DYYTEXT_POINTER=1"
#endif

#ifndef OCTAVE_CONF_DL_LD
#define OCTAVE_CONF_DL_LD "g++"
#endif

#ifndef OCTAVE_CONF_DL_LDFLAGS
#define OCTAVE_CONF_DL_LDFLAGS "-shared"
#endif

#ifndef OCTAVE_CONF_DL_LIBS
#define OCTAVE_CONF_DL_LIBS "-ldl"
#endif

#ifndef OCTAVE_CONF_EXEEXT
#define OCTAVE_CONF_EXEEXT ""
#endif

#ifndef OCTAVE_CONF_F77
#define OCTAVE_CONF_F77 "gfortran"
#endif

#ifndef OCTAVE_CONF_F77_FLOAT_STORE_FLAG
#define OCTAVE_CONF_F77_FLOAT_STORE_FLAG "-ffloat-store"
#endif

#ifndef OCTAVE_CONF_F77_INTEGER_8_FLAG
#define OCTAVE_CONF_F77_INTEGER_8_FLAG "-fdefault-integer-8"
#endif

#ifndef OCTAVE_CONF_FC
#define OCTAVE_CONF_FC "gfortran"
#endif

#ifndef OCTAVE_CONF_FFLAGS
#define OCTAVE_CONF_FFLAGS "-O"
#endif

#ifndef OCTAVE_CONF_FFTW3_CPPFLAGSS
#define OCTAVE_CONF_FFTW3_CPPFLAGS ""
#endif

#ifndef OCTAVE_CONF_FFTW3_LDFLAGSS
#define OCTAVE_CONF_FFTW3_LDFLAGS ""
#endif

#ifndef OCTAVE_CONF_FFTW3_LIBS
#define OCTAVE_CONF_FFTW3_LIBS ""
#endif

#ifndef OCTAVE_CONF_FFTW3F_CPPFLAGSS
#define OCTAVE_CONF_FFTW3F_CPPFLAGS ""
#endif

#ifndef OCTAVE_CONF_FFTW3F_LDFLAGSS
#define OCTAVE_CONF_FFTW3F_LDFLAGS ""
#endif

#ifndef OCTAVE_CONF_FFTW3F_LIBS
#define OCTAVE_CONF_FFTW3F_LIBS ""
#endif

#ifndef OCTAVE_CONF_FLIBS
#define OCTAVE_CONF_FLIBS "-L/mnt/oqtansTools/oqtans_dep/lib/ -L/usr/lib/gcc/x86_64-redhat-linux/4.4.6 -L/usr/lib/gcc/x86_64-redhat-linux/4.4.6/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/4.4.6/../../.. -lgfortranbegin -lgfortran -lm"
#endif

#ifndef OCTAVE_CONF_FPICFLAG
#define OCTAVE_CONF_FPICFLAG "-fPIC"
#endif

#ifndef OCTAVE_CONF_FT2_LIBS
#define OCTAVE_CONF_FT2_LIBS ""
#endif

#ifndef OCTAVE_CONF_GLPK_CPPFLAGS
#define OCTAVE_CONF_GLPK_CPPFLAGS "-I/mnt/oqtansTools/oqtans_dep/include"
#endif

#ifndef OCTAVE_CONF_GLPK_LDFLAGS
#define OCTAVE_CONF_GLPK_LDFLAGS "-L/mnt/oqtansTools/oqtans_dep/lib"
#endif

#ifndef OCTAVE_CONF_GLPK_LIBS
#define OCTAVE_CONF_GLPK_LIBS "-lglpk"
#endif

#ifndef OCTAVE_CONF_GNUPLOT
#define OCTAVE_CONF_GNUPLOT "gnuplot"
#endif

#ifndef OCTAVE_CONF_GRAPHICS_LIBS
#define OCTAVE_CONF_GRAPHICS_LIBS ""
#endif

#ifndef OCTAVE_CONF_HDF5_CPPFLAGS
#define OCTAVE_CONF_HDF5_CPPFLAGS ""
#endif

#ifndef OCTAVE_CONF_HDF5_LDFLAGS
#define OCTAVE_CONF_HDF5_LDFLAGS ""
#endif

#ifndef OCTAVE_CONF_HDF5_LIBS
#define OCTAVE_CONF_HDF5_LIBS ""
#endif

#ifndef OCTAVE_CONF_INCFLAGS
#define OCTAVE_CONF_INCFLAGS ""
#endif

#ifndef OCTAVE_CONF_INCLUDEDIR
#define OCTAVE_CONF_INCLUDEDIR "/mnt/oqtansTools/oqtans_dep/octave-3.4.3/include"
#endif

#ifndef OCTAVE_CONF_LAPACK_LIBS
#define OCTAVE_CONF_LAPACK_LIBS "-llapack"
#endif

#ifndef OCTAVE_CONF_LDFLAGS
#define OCTAVE_CONF_LDFLAGS "-L/mnt/oqtansTools/oqtans_dep/lib/"
#endif

#ifndef OCTAVE_CONF_LD_CXX
#define OCTAVE_CONF_LD_CXX "g++"
#endif

#ifndef OCTAVE_CONF_LD_STATIC_FLAG
#define OCTAVE_CONF_LD_STATIC_FLAG ""
#endif

#ifndef OCTAVE_CONF_LEXLIB
#define OCTAVE_CONF_LEXLIB ""
#endif

#ifndef OCTAVE_CONF_LEX
#define OCTAVE_CONF_LEX "flex"
#endif

#ifndef OCTAVE_CONF_LFLAGS
#define OCTAVE_CONF_LFLAGS "-I"
#endif

#ifndef OCTAVE_CONF_LIBCRUFT
#define OCTAVE_CONF_LIBCRUFT "-lcruft"
#endif

#ifndef OCTAVE_CONF_LIBEXT
#define OCTAVE_CONF_LIBEXT "a"
#endif

#ifndef OCTAVE_CONF_LIBFLAGS
#define OCTAVE_CONF_LIBFLAGS "-L.."
#endif

#ifndef OCTAVE_CONF_LIBOCTAVE
#define OCTAVE_CONF_LIBOCTAVE "-loctave"
#endif

#ifndef OCTAVE_CONF_LIBOCTINTERP
#define OCTAVE_CONF_LIBOCTINTERP "-loctinterp"
#endif

#ifndef OCTAVE_CONF_LIBPLPLOT
#define OCTAVE_CONF_LIBPLPLOT %OCTAVE_CONF_LIBPLPLOT%
#endif

#ifndef OCTAVE_CONF_LIBS
#define OCTAVE_CONF_LIBS "-lm  -L/mnt/oqtansTools/oqtans_dep/lib/"
#endif

#ifndef OCTAVE_CONF_LN_S
#define OCTAVE_CONF_LN_S "ln -s"
#endif

#ifndef OCTAVE_CONF_MAGICK_CPPFLAGS
#define OCTAVE_CONF_MAGICK_CPPFLAGS ""
#endif

#ifndef OCTAVE_CONF_MAGICK_LDFLAGS
#define OCTAVE_CONF_MAGICK_LDFLAGS ""
#endif

#ifndef OCTAVE_CONF_MAGICK_LIBS
#define OCTAVE_CONF_MAGICK_LIBS ""
#endif

#ifndef OCTAVE_CONF_MKOCTFILE_DL_LDFLAGS
#define OCTAVE_CONF_MKOCTFILE_DL_LDFLAGS "-shared -Wl,-Bsymbolic"
#endif

#ifndef OCTAVE_CONF_OCTINCLUDEDIR
#define OCTAVE_CONF_OCTINCLUDEDIR "/mnt/oqtansTools/oqtans_dep/octave-3.4.3/include/octave-3.4.3/octave"
#endif

#ifndef OCTAVE_CONF_OCTLIBDIR
#define OCTAVE_CONF_OCTLIBDIR "/mnt/oqtansTools/oqtans_dep/octave-3.4.3/lib/octave/3.4.3"
#endif

#ifndef OCTAVE_CONF_OPENGL_LIBS
#define OCTAVE_CONF_OPENGL_LIBS ""
#endif

#ifndef OCTAVE_CONF_PREFIX
#define OCTAVE_CONF_PREFIX "/mnt/oqtansTools/oqtans_dep/octave-3.4.3"
#endif

#ifndef OCTAVE_CONF_PTHREAD_CFLAGS
#define OCTAVE_CONF_PTHREAD_CFLAGS "-pthread"
#endif

#ifndef OCTAVE_CONF_PTHREAD_LIBS
#define OCTAVE_CONF_PTHREAD_LIBS ""
#endif

#ifndef OCTAVE_CONF_QHULL_CPPFLAGS
#define OCTAVE_CONF_QHULL_CPPFLAGS ""
#endif

#ifndef OCTAVE_CONF_QHULL_LDFLAGS
#define OCTAVE_CONF_QHULL_LDFLAGS ""
#endif

#ifndef OCTAVE_CONF_QHULL_LIBS
#define OCTAVE_CONF_QHULL_LIBS ""
#endif

#ifndef OCTAVE_CONF_QRUPDATE_CPPFLAGS
#define OCTAVE_CONF_QRUPDATE_CPPFLAGS "-I/mnt/oqtansTools/oqtans_dep/include/"
#endif

#ifndef OCTAVE_CONF_QRUPDATE_LDFLAGS
#define OCTAVE_CONF_QRUPDATE_LDFLAGS "-L/mnt/oqtansTools/oqtans_dep/lib/"
#endif

#ifndef OCTAVE_CONF_QRUPDATE_LIBS
#define OCTAVE_CONF_QRUPDATE_LIBS "-lqrupdate"
#endif

#ifndef OCTAVE_CONF_RANLIB
#define OCTAVE_CONF_RANLIB "ranlib"
#endif

#ifndef OCTAVE_CONF_RDYNAMIC_FLAG
#define OCTAVE_CONF_RDYNAMIC_FLAG "-rdynamic"
#endif

#ifndef OCTAVE_CONF_READLINE_LIBS
#define OCTAVE_CONF_READLINE_LIBS ""
#endif

#ifndef OCTAVE_CONF_REGEX_LIBS
#define OCTAVE_CONF_REGEX_LIBS "-lpcre"
#endif

#ifndef OCTAVE_CONF_RLD_FLAG
#define OCTAVE_CONF_RLD_FLAG "-Wl,-rpath -Wl,/mnt/oqtansTools/oqtans_dep/octave-3.4.3/lib/octave/3.4.3"
#endif

#ifndef OCTAVE_CONF_SED
#define OCTAVE_CONF_SED "/bin/sed"
#endif

#ifndef OCTAVE_CONF_SHARED_LIBS
#define OCTAVE_CONF_SHARED_LIBS ""
#endif

#ifndef OCTAVE_CONF_SHLEXT
#define OCTAVE_CONF_SHLEXT "so"
#endif

#ifndef OCTAVE_CONF_SHLEXT_VER
#define OCTAVE_CONF_SHLEXT_VER "so.3.4.3"
#endif

#ifndef OCTAVE_CONF_SH_LD
#define OCTAVE_CONF_SH_LD "g++"
#endif

#ifndef OCTAVE_CONF_SH_LDFLAGS
#define OCTAVE_CONF_SH_LDFLAGS "-shared"
#endif

#ifndef OCTAVE_CONF_SONAME_FLAGS
#define OCTAVE_CONF_SONAME_FLAGS "-Wl,-soname -Wl,oct-conf.h"
#endif

#ifndef OCTAVE_CONF_STATIC_LIBS
#define OCTAVE_CONF_STATIC_LIBS ""
#endif

#ifndef OCTAVE_CONF_TERM_LIBS
#define OCTAVE_CONF_TERM_LIBS "-lncurses"
#endif

#ifndef OCTAVE_CONF_UGLY_DEFS
#define OCTAVE_CONF_UGLY_DEFS "-DPACKAGE_NAME=\"GNU Octave\" -DPACKAGE_TARNAME=\"octave\" -DPACKAGE_VERSION=\"3.4.3\" -DPACKAGE_STRING=\"GNU Octave 3.4.3\" -DPACKAGE_BUGREPORT=\"http://octave.org/bugs.html\" -DPACKAGE_URL=\"http://www.gnu.org/software/octave/\" -DPACKAGE=\"octave\" -DVERSION=\"3.4.3\" -DOCTAVE_SOURCE=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_DARWIN_C_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DSEPCHAR=':' -DSEPCHAR_STR=\":\" -DSIZEOF_VOID_P=8 -DSIZEOF_INT=4 -DSIZEOF_LONG=8 -DIDX_TYPE_LONG=1 -DOCTAVE_IDX_TYPE=long -DUSE_64_BIT_IDX_T=1 -D__NO_MATH_INLINES=1 -DCXX_NEW_FRIEND_TEMPLATE_DECL=1 -DCXX_ISO_COMPLIANT_LIBRARY=1 -DHAVE_FSEEKO=1 -DHAVE_ALLOCA_H=1 -DHAVE_ALLOCA=1 -DHAVE_CANONICALIZE_FILE_NAME=1 -DHAVE_GETCWD=1 -DHAVE_READLINK=1 -DHAVE_REALPATH=1 -DHAVE_CHOWN=1 -DHAVE_FCHOWN=1 -DHAVE_FCHDIR=1 -DHAVE_FCNTL=1 -DHAVE_SYMLINK=1 -DHAVE_FDOPENDIR=1 -DHAVE_MEMPCPY=1 -DHAVE_BTOWC=1 -DHAVE_ISBLANK=1 -DHAVE_ISWCTYPE=1 -DHAVE_MBSRTOWCS=1 -DHAVE_WMEMCHR=1 -DHAVE_WMEMCPY=1 -DHAVE_WMEMPCPY=1 -DHAVE___FPURGE=1 -DHAVE___FREADING=1 -DHAVE_GETDTABLESIZE=1 -DHAVE_GETLOGIN_R=1 -DHAVE_GETTIMEOFDAY=1 -DHAVE_FSTATAT=1 -DHAVE_GETPWNAM_R=1 -DHAVE_LINK=1 -DHAVE_LSTAT=1 -DHAVE_MBSINIT=1 -DHAVE_MBRTOWC=1 -DHAVE_MPROTECT=1 -DHAVE_MKFIFO=1 -DHAVE_MKSTEMP=1 -DHAVE_ALARM=1 -DHAVE_FCHMODAT=1 -DHAVE_MKDIRAT=1 -DHAVE_OPENAT=1 -DHAVE_UNLINKAT=1 -DHAVE_SIGACTION=1 -DHAVE_SIGALTSTACK=1 -DHAVE_SIGINTERRUPT=1 -DHAVE_SLEEP=1 -DHAVE_STRDUP=1 -DHAVE_TZSET=1 -DHAVE_STRPTIME=1 -DHAVE_LOCALTIME_R=1 -DHAVE_TIMES=1 -DHAVE_PIPE=1 -DHAVE_SNPRINTF=1 -DHAVE_ISWCNTRL=1 -DFUNC_REALPATH_WORKS=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SYS_SOCKET_H=1 -DHAVE_DIRENT_H=1 -DHAVE_WCTYPE_H=1 -DHAVE_NETDB_H=1 -DHAVE_GETOPT_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_SYS_CDEFS_H=1 -DHAVE_MATH_H=1 -DHAVE_SYS_MMAN_H=1 -DHAVE_SYS_SELECT_H=1 -DHAVE_WCHAR_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TIMES_H=1 -DHAVE_SYS_UIO_H=1 -DHAVE_FEATURES_H=1 -DHAVE_UNISTD_H=1 -DHAVE_CHOWN=1 -DHAVE_DECL_STRERROR_R=1 -DHAVE_STRERROR_R=1 -DSTRERROR_R_CHAR_P=1 -DHAVE_DECL_FCHDIR=1 -DHAVE_WORKING_O_NOATIME=1 -DHAVE_WORKING_O_NOFOLLOW=1 -DHAVE_DECL_STRMODE=0 -DHAVE_MBSTATE_T=1 -DHAVE_DECL_FSEEKO=1 -DHAVE_DECL_FTELLO=1 -DHAVE_DECL_GETCWD=1 -DHAVE_DECL_GETLOGIN_R=1 -DHAVE_DECL_GETLOGIN=1 -DHAVE_GETOPT_H=1 -DHAVE_GETOPT_LONG_ONLY=1 -D__GETOPT_PREFIX=rpl_ -DHAVE_DECL_GETENV=1 -Drestrict=__restrict -DHAVE_RAW_DECL_GETTIMEOFDAY=1 -DHAVE_LANGINFO_CODESET=1 -DHAVE_DECL_GETC_UNLOCKED=1 -DLSTAT_FOLLOWS_SLASHED_SYMLINK=1 -DHAVE_STDLIB_H=1 -DMALLOC_0_IS_NONNULL=1 -DHAVE_UNSIGNED_LONG_LONG_INT=1 -DHAVE_LONG_LONG_INT=1 -DHAVE_MAP_ANONYMOUS=1 -DHAVE_DECL_MEMRCHR=1 -DHAVE_RAW_DECL_PSELECT=1 -DHAVE_RAW_DECL_SELECT=1 -DPROMOTED_MODE_T=mode_t -DHAVE_SIGSET_T=1 -DHAVE__BOOL=1 -DHAVE_WCHAR_T=1 -DHAVE_DECL_STRDUP=1 -DHAVE_STRUCT_TM_TM_ZONE=1 -DHAVE_TM_ZONE=1 -DHAVE_TM_GMTOFF=1 -DHAVE_RAW_DECL_FFSL=1 -DHAVE_RAW_DECL_FFSLL=1 -DHAVE_RAW_DECL_MEMMEM=1 -DHAVE_RAW_DECL_MEMPCPY=1 -DHAVE_RAW_DECL_MEMRCHR=1 -DHAVE_RAW_DECL_RAWMEMCHR=1 -DHAVE_RAW_DECL_STPCPY=1 -DHAVE_RAW_DECL_STPNCPY=1 -DHAVE_RAW_DECL_STRCHRNUL=1 -DHAVE_RAW_DECL_STRDUP=1 -DHAVE_RAW_DECL_STRNCAT=1 -DHAVE_RAW_DECL_STRNDUP=1 -DHAVE_RAW_DECL_STRNLEN=1 -DHAVE_RAW_DECL_STRPBRK=1 -DHAVE_RAW_DECL_STRSEP=1 -DHAVE_RAW_DECL_STRCASESTR=1 -DHAVE_RAW_DECL_STRTOK_R=1 -DHAVE_RAW_DECL_STRERROR_R=1 -DHAVE_RAW_DECL_STRSIGNAL=1 -DHAVE_RAW_DECL_STRVERSCMP=1 -DHAVE_RAW_DECL_FFS=1 -DHAVE_RAW_DECL_STRCASECMP=1 -DHAVE_RAW_DECL_STRNCASECMP=1 -DHAVE_DECL_LOCALTIME_R=0 -DHAVE_WINT_T=1 -DHAVE_INTTYPES_H_WITH_UINTMAX=1 -DHAVE_STDINT_H_WITH_UINTMAX=1 -DHAVE_INTMAX_T=1 -DHAVE_SNPRINTF=1 -DHAVE_STRNLEN=1 -DHAVE_WCSLEN=1 -DHAVE_WCSNLEN=1 -DHAVE_MBRTOWC=1 -DHAVE_WCRTOMB=1 -DHAVE_DECL__SNPRINTF=0 -DHAVE_SNPRINTF_RETVAL_C99=1 -DHAVE_DECL_VSNPRINTF=1 -DHAVE_ALLOCA=1 -DGNULIB_CANONICALIZE_LGPL=1 -DGNULIB_TEST_CANONICALIZE_FILE_NAME=1 -DGNULIB_TEST_REALPATH=1 -DGNULIB_TEST_CHDIR=1 -DGNULIB_TEST_CHOWN=1 -DGNULIB_TEST_CLOEXEC=1 -DGNULIB_TEST_CLOSE=1 -DHAVE_CLOSEDIR=1 -DGNULIB_TEST_CLOSEDIR=1 -DD_INO_IN_DIRENT=1 -DHAVE_STRUCT_DIRENT_D_TYPE=1 -DHAVE_RAW_DECL_ALPHASORT=1 -DHAVE_RAW_DECL_CLOSEDIR=1 -DHAVE_RAW_DECL_DIRFD=1 -DHAVE_RAW_DECL_FDOPENDIR=1 -DHAVE_RAW_DECL_OPENDIR=1 -DHAVE_RAW_DECL_READDIR=1 -DHAVE_RAW_DECL_REWINDDIR=1 -DHAVE_RAW_DECL_SCANDIR=1 -DHAVE_DIRFD=1 -DHAVE_DECL_DIRFD=1 -DGNULIB_TEST_DIRFD=1 -DGNULIB_TEST_DUP=1 -DHAVE_DUP2=1 -DGNULIB_TEST_DUP2=1 -DGNULIB_TEST_FCHDIR=1 -DGNULIB_TEST_FCLOSE=1 -DGNULIB_TEST_FCNTL=1 -DHAVE_RAW_DECL_FCNTL=1 -DHAVE_RAW_DECL_OPENAT=1 -DHAVE_DECL_FDOPENDIR=1 -DGNULIB_TEST_FDOPENDIR=1 -DGNULIB_FDOPENDIR=1 -DGNULIB_FFLUSH=1 -DGNULIB_TEST_FFLUSH=1 -DGNULIB_TEST_FLOOR=1 -Dfnmatch=posix_fnmatch -DHAVE_DECL_ISBLANK=1 -DGNULIB_TEST_FOPEN=1 -DHAVE_DECL_FPURGE=0 -DGNULIB_TEST_FPURGE=1 -DGNULIB_TEST_FSEEK=1 -DGNULIB_TEST_FSEEKO=1 -DGNULIB_TEST_FSTAT=1 -DGNULIB_TEST_FTELL=1 -DGNULIB_TEST_FTELLO=1 -DHAVE_PARTLY_WORKING_GETCWD=1 -DHAVE_GETPAGESIZE=1 -DGNULIB_GETCWD=1 -DGNULIB_TEST_GETCWD=1 -DGNULIB_TEST_GETCWD=1 -DGNULIB_TEST_GETDTABLESIZE=1 -DHAVE_GETHOSTNAME=1 -DGNULIB_TEST_GETHOSTNAME=1 -DGNULIB_TEST_GETLOGIN_R=1 -DGNULIB_TEST_GETOPT_GNU=1 -D__GETOPT_PREFIX=rpl_ -DGETTIMEOFDAY_TIMEZONE=struct timezone -DGNULIB_TEST_GETTIMEOFDAY=1 -DHAVE_GLOB_H=1 -DHAVE_LCHOWN=1 -DGNULIB_TEST_LCHOWN=1 -DGNULIB_TEST_LINK=1 -DGNULIB_TEST_LSEEK=1 -DGNULIB_TEST_LSTAT=1 -DHAVE_MALLOC_POSIX=1 -DGNULIB_TEST_MALLOC_POSIX=1 -DHAVE_RAW_DECL_ACOSL=1 -DHAVE_RAW_DECL_ASINL=1 -DHAVE_RAW_DECL_ATANL=1 -DHAVE_RAW_DECL_CEILF=1 -DHAVE_RAW_DECL_CEILL=1 -DHAVE_RAW_DECL_COSL=1 -DHAVE_RAW_DECL_EXPL=1 -DHAVE_RAW_DECL_FLOORF=1 -DHAVE_RAW_DECL_FLOORL=1 -DHAVE_RAW_DECL_FREXPL=1 -DHAVE_RAW_DECL_LDEXPL=1 -DHAVE_RAW_DECL_LOGB=1 -DHAVE_RAW_DECL_LOGL=1 -DHAVE_RAW_DECL_ROUND=1 -DHAVE_RAW_DECL_ROUNDF=1 -DHAVE_RAW_DECL_ROUNDL=1 -DHAVE_RAW_DECL_SINL=1 -DHAVE_RAW_DECL_SQRTL=1 -DHAVE_RAW_DECL_TANL=1 -DHAVE_RAW_DECL_TRUNC=1 -DHAVE_RAW_DECL_TRUNCF=1 -DHAVE_RAW_DECL_TRUNCL=1 -DGNULIB_TEST_MBRTOWC=1 -DGNULIB_TEST_MBSINIT=1 -DGNULIB_TEST_MBSRTOWCS=1 -DGNULIB_TEST_MEMCHR=1 -DHAVE_MEMPCPY=1 -DGNULIB_TEST_MEMPCPY=1 -DHAVE_MEMRCHR=1 -DGNULIB_TEST_MEMRCHR=1 -DGNULIB_TEST_MKFIFO=1 -DGNULIB_TEST_MKSTEMP=1 -DGNULIB_TEST_MKTIME=1 -DHAVE_BUG_BIG_NANOSLEEP=1 -DGNULIB_TEST_NANOSLEEP=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_SYS_SYSCTL_H=1 -DHAVE_SCHED_GETAFFINITY=1 -DHAVE_SYSCTL=1 -DHAVE_SCHED_GETAFFINITY_LIKE_GLIBC=1 -DGNULIB_TEST_OPEN=1 -DGNULIB_OPENAT=1 -DHAVE_OPENDIR=1 -DGNULIB_TEST_OPENDIR=1 -DHAVE_DECL_PROGRAM_INVOCATION_NAME=1 -DHAVE_DECL_PROGRAM_INVOCATION_SHORT_NAME=1 -DHAVE_RAISE=1 -DGNULIB_TEST_RAISE=1 -DHAVE_READDIR=1 -DGNULIB_TEST_READDIR=1 -DGNULIB_TEST_READLINK=1 -DHAVE_REALLOC_POSIX=1 -DGNULIB_TEST_REALLOC_POSIX=1 -DGNULIB_TEST_RENAME=1 -DGNULIB_TEST_RMDIR=1 -DHAVE_DECL_ROUND=1 -DGNULIB_TEST_ROUND=1 -DHAVE_DECL_ROUNDF=1 -DGNULIB_TEST_ROUNDF=1 -DGNULIB_TEST_SELECT=1 -DHAVE_STRUCT_SIGACTION_SA_SIGACTION=1 -DGNULIB_TEST_SIGACTION=1 -DHAVE_RAW_DECL_PTHREAD_SIGMASK=1 -DHAVE_RAW_DECL_SIGACTION=1 -DHAVE_RAW_DECL_SIGADDSET=1 -DHAVE_RAW_DECL_SIGDELSET=1 -DHAVE_RAW_DECL_SIGEMPTYSET=1 -DHAVE_RAW_DECL_SIGFILLSET=1 -DHAVE_RAW_DECL_SIGISMEMBER=1 -DHAVE_RAW_DECL_SIGPENDING=1 -DHAVE_RAW_DECL_SIGPROCMASK=1 -DGNULIB_TEST_SIGPROCMASK=1 -DHAVE_STDINT_H=1 -DHAVE_DECL_SLEEP=1 -DGNULIB_TEST_SLEEP=1 -DGNULIB_TEST_STAT=1 -DHAVE_RAW_DECL_DPRINTF=1 -DHAVE_RAW_DECL_FSEEKO=1 -DHAVE_RAW_DECL_FTELLO=1 -DHAVE_RAW_DECL_GETDELIM=1 -DHAVE_RAW_DECL_GETLINE=1 -DHAVE_RAW_DECL_PCLOSE=1 -DHAVE_RAW_DECL_POPEN=1 -DHAVE_RAW_DECL_RENAMEAT=1 -DHAVE_RAW_DECL_SNPRINTF=1 -DHAVE_RAW_DECL_TMPFILE=1 -DHAVE_RAW_DECL_VDPRINTF=1 -DHAVE_RAW_DECL_VSNPRINTF=1 -DHAVE_RAW_DECL__EXIT=1 -DHAVE_RAW_DECL_ATOLL=1 -DHAVE_RAW_DECL_CANONICALIZE_FILE_NAME=1 -DHAVE_RAW_DECL_GETLOADAVG=1 -DHAVE_RAW_DECL_GETSUBOPT=1 -DHAVE_RAW_DECL_GRANTPT=1 -DHAVE_RAW_DECL_MKDTEMP=1 -DHAVE_RAW_DECL_MKOSTEMP=1 -DHAVE_RAW_DECL_MKOSTEMPS=1 -DHAVE_RAW_DECL_MKSTEMP=1 -DHAVE_RAW_DECL_MKSTEMPS=1 -DHAVE_RAW_DECL_PTSNAME=1 -DHAVE_RAW_DECL_RANDOM_R=1 -DHAVE_RAW_DECL_SRANDOM_R=1 -DHAVE_RAW_DECL_SETSTATE_R=1 -DHAVE_RAW_DECL_REALPATH=1 -DHAVE_RAW_DECL_RPMATCH=1 -DHAVE_RAW_DECL_SETENV=1 -DHAVE_RAW_DECL_STRTOD=1 -DHAVE_RAW_DECL_STRTOLL=1 -DHAVE_RAW_DECL_STRTOULL=1 -DHAVE_RAW_DECL_UNLOCKPT=1 -DHAVE_RAW_DECL_UNSETENV=1 -DHAVE_STRCASECMP=1 -DHAVE_STRNCASECMP=1 -DHAVE_DECL_STRNCASECMP=1 -DGNULIB_TEST_STRDUP=1 -DGNULIB_STRERROR=1 -DGNULIB_TEST_STRERROR=1 -Dmy_strftime=nstrftime -DGNULIB_TEST_STRPTIME=1 -DGNULIB_TEST_SYMLINK=1 -DHAVE_RAW_DECL_PSELECT=1 -DHAVE_RAW_DECL_SELECT=1 -DHAVE_SHUTDOWN=1 -DHAVE_STRUCT_SOCKADDR_STORAGE=1 -DHAVE_SA_FAMILY_T=1 -DHAVE_STRUCT_SOCKADDR_STORAGE_SS_FAMILY=1 -DHAVE_RAW_DECL_SOCKET=1 -DHAVE_RAW_DECL_CONNECT=1 -DHAVE_RAW_DECL_ACCEPT=1 -DHAVE_RAW_DECL_BIND=1 -DHAVE_RAW_DECL_GETPEERNAME=1 -DHAVE_RAW_DECL_GETSOCKNAME=1 -DHAVE_RAW_DECL_GETSOCKOPT=1 -DHAVE_RAW_DECL_LISTEN=1 -DHAVE_RAW_DECL_RECV=1 -DHAVE_RAW_DECL_SEND=1 -DHAVE_RAW_DECL_RECVFROM=1 -DHAVE_RAW_DECL_SENDTO=1 -DHAVE_RAW_DECL_SETSOCKOPT=1 -DHAVE_RAW_DECL_SHUTDOWN=1 -DHAVE_RAW_DECL_ACCEPT4=1 -DHAVE_RAW_DECL_FCHMODAT=1 -DHAVE_RAW_DECL_FSTAT=1 -DHAVE_RAW_DECL_FSTATAT=1 -DHAVE_RAW_DECL_FUTIMENS=1 -DHAVE_RAW_DECL_LCHMOD=1 -DHAVE_RAW_DECL_LSTAT=1 -DHAVE_RAW_DECL_MKDIRAT=1 -DHAVE_RAW_DECL_MKFIFO=1 -DHAVE_RAW_DECL_MKFIFOAT=1 -DHAVE_RAW_DECL_MKNOD=1 -DHAVE_RAW_DECL_MKNODAT=1 -DHAVE_RAW_DECL_STAT=1 -DHAVE_RAW_DECL_UTIMENSAT=1 -DHAVE_STRUCT_TMS=1 -DHAVE_RAW_DECL_TIMES=1 -DGNULIB_TEST_TIME_R=1 -DHAVE___SECURE_GETENV=1 -DGNULIB_TEST_TMPFILE=1 -DHAVE_DECL_TRUNC=1 -DGNULIB_TEST_TRUNC=1 -DHAVE_DECL_TRUNCF=1 -DGNULIB_TEST_TRUNCF=1 -DHAVE_RAW_DECL_CHDIR=1 -DHAVE_RAW_DECL_CHOWN=1 -DHAVE_RAW_DECL_DUP=1 -DHAVE_RAW_DECL_DUP2=1 -DHAVE_RAW_DECL_DUP3=1 -DHAVE_RAW_DECL_ENVIRON=1 -DHAVE_RAW_DECL_EUIDACCESS=1 -DHAVE_RAW_DECL_FACCESSAT=1 -DHAVE_RAW_DECL_FCHDIR=1 -DHAVE_RAW_DECL_FCHOWNAT=1 -DHAVE_RAW_DECL_FDATASYNC=1 -DHAVE_RAW_DECL_FSYNC=1 -DHAVE_RAW_DECL_FTRUNCATE=1 -DHAVE_RAW_DECL_GETCWD=1 -DHAVE_RAW_DECL_GETDOMAINNAME=1 -DHAVE_RAW_DECL_GETDTABLESIZE=1 -DHAVE_RAW_DECL_GETGROUPS=1 -DHAVE_RAW_DECL_GETHOSTNAME=1 -DHAVE_RAW_DECL_GETLOGIN=1 -DHAVE_RAW_DECL_GETLOGIN_R=1 -DHAVE_RAW_DECL_GETPAGESIZE=1 -DHAVE_RAW_DECL_GETUSERSHELL=1 -DHAVE_RAW_DECL_SETUSERSHELL=1 -DHAVE_RAW_DECL_ENDUSERSHELL=1 -DHAVE_RAW_DECL_GROUP_MEMBER=1 -DHAVE_RAW_DECL_LCHOWN=1 -DHAVE_RAW_DECL_LINK=1 -DHAVE_RAW_DECL_LINKAT=1 -DHAVE_RAW_DECL_LSEEK=1 -DHAVE_RAW_DECL_PIPE=1 -DHAVE_RAW_DECL_PIPE2=1 -DHAVE_RAW_DECL_PREAD=1 -DHAVE_RAW_DECL_PWRITE=1 -DHAVE_RAW_DECL_READLINK=1 -DHAVE_RAW_DECL_READLINKAT=1 -DHAVE_RAW_DECL_RMDIR=1 -DHAVE_RAW_DECL_SLEEP=1 -DHAVE_RAW_DECL_SYMLINK=1 -DHAVE_RAW_DECL_SYMLINKAT=1 -DHAVE_RAW_DECL_TTYNAME_R=1 -DHAVE_RAW_DECL_UNLINK=1 -DHAVE_RAW_DECL_UNLINKAT=1 -DHAVE_RAW_DECL_USLEEP=1 -DGNULIB_TEST_UNLINK=1 -DHAVE_VSNPRINTF=1 -DGNULIB_TEST_VSNPRINTF=1 -DHAVE_RAW_DECL_BTOWC=1 -DHAVE_RAW_DECL_WCTOB=1 -DHAVE_RAW_DECL_MBSINIT=1 -DHAVE_RAW_DECL_MBRTOWC=1 -DHAVE_RAW_DECL_MBRLEN=1 -DHAVE_RAW_DECL_MBSRTOWCS=1 -DHAVE_RAW_DECL_MBSNRTOWCS=1 -DHAVE_RAW_DECL_WCRTOMB=1 -DHAVE_RAW_DECL_WCSRTOMBS=1 -DHAVE_RAW_DECL_WCSNRTOMBS=1 -DHAVE_RAW_DECL_WCWIDTH=1 -DHAVE_RAW_DECL_WMEMCHR=1 -DHAVE_RAW_DECL_WMEMCMP=1 -DHAVE_RAW_DECL_WMEMCPY=1 -DHAVE_RAW_DECL_WMEMMOVE=1 -DHAVE_RAW_DECL_WMEMSET=1 -DHAVE_RAW_DECL_WCSLEN=1 -DHAVE_RAW_DECL_WCSNLEN=1 -DHAVE_RAW_DECL_WCSCPY=1 -DHAVE_RAW_DECL_WCPCPY=1 -DHAVE_RAW_DECL_WCSNCPY=1 -DHAVE_RAW_DECL_WCPNCPY=1 -DHAVE_RAW_DECL_WCSCAT=1 -DHAVE_RAW_DECL_WCSNCAT=1 -DHAVE_RAW_DECL_WCSCMP=1 -DHAVE_RAW_DECL_WCSNCMP=1 -DHAVE_RAW_DECL_WCSCASECMP=1 -DHAVE_RAW_DECL_WCSNCASECMP=1 -DHAVE_RAW_DECL_WCSCOLL=1 -DHAVE_RAW_DECL_WCSXFRM=1 -DHAVE_RAW_DECL_WCSDUP=1 -DHAVE_RAW_DECL_WCSCHR=1 -DHAVE_RAW_DECL_WCSRCHR=1 -DHAVE_RAW_DECL_WCSCSPN=1 -DHAVE_RAW_DECL_WCSSPN=1 -DHAVE_RAW_DECL_WCSPBRK=1 -DHAVE_RAW_DECL_WCSSTR=1 -DHAVE_RAW_DECL_WCSTOK=1 -DHAVE_RAW_DECL_WCSWIDTH=1 -DHAVE_TOWLOWER=1 -DHAVE_RAW_DECL_WCTYPE=1 -DHAVE_RAW_DECL_ISWCTYPE=1 -DHAVE_RAW_DECL_WCTRANS=1 -DHAVE_RAW_DECL_TOWCTRANS=1 -DHAVE_STDINT_H=1 -DHAVE_PTHREAD=1 -DFLOAT_TRUNCATE= -DHAVE_LIBM=1 -DF77_FUNC(name,NAME)=name ## _ -DF77_FUNC_(name,NAME)=name ## _ -DHAVE_IEEE754_DATA_FORMAT=1 -DHAVE_CXX_COMPLEX_SETTERS=1 -DHAVE_CXX_COMPLEX_REFERENCE_ACCESSORS=1 -DHAVE_PCRE_COMPILE=1 -DHAVE_ZLIB_H=1 -DHAVE_Z=1 -DHAVE_GLPK_H=1 -DHAVE_GLPK=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_QRUPDATE=1 -DHAVE_QRUPDATE_LUU=1 -DHAVE_SUITESPARSE_AMD_H=1 -DHAVE_AMD=1 -DHAVE_SUITESPARSE_CAMD_H=1 -DHAVE_CAMD=1 -DHAVE_SUITESPARSE_COLAMD_H=1 -DHAVE_COLAMD=1 -DHAVE_SUITESPARSE_CCOLAMD_H=1 -DHAVE_CCOLAMD=1 -DHAVE_SUITESPARSE_CHOLMOD_H=1 -DHAVE_SUITESPARSE_CS_H=1 -DHAVE_CXSPARSE=1 -DHAVE_GETPWNAM=1 -DHAVE_DEV_T=1 -DHAVE_INO_T=1 -DHAVE_LONG_LONG_INT=1 -DHAVE_UNSIGNED_LONG_LONG_INT=1 -DSIZEOF_SHORT=2 -DSIZEOF_INT=4 -DSIZEOF_LONG=8 -DSIZEOF_LONG_LONG=8 -DHAVE_ALLOCA_H=1 -DHAVE_ALLOCA=1 -DHAVE_PLACEMENT_DELETE=1 -DHAVE_DYNAMIC_AUTO_ARRAYS=1 -DHAVE_FAST_INT_OPS=1 -DSIZEOF_LONG_DOUBLE=16 -DHAVE_DIRENT_H=1 -DHAVE_SYS_WAIT_H=1 -DHAVE_CURSES_H=1 -DHAVE_DLFCN_H=1 -DHAVE_GRP_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_LOCALE_H=1 -DHAVE_MEMORY_H=1 -DHAVE_NCURSES_H=1 -DHAVE_POLL_H=1 -DHAVE_PTHREAD_H=1 -DHAVE_PWD_H=1 -DHAVE_SYS_IOCTL_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_SYS_POLL_H=1 -DHAVE_SYS_RESOURCE_H=1 -DHAVE_SYS_SELECT_H=1 -DHAVE_SYS_UTSNAME_H=1 -DHAVE_TERMCAP_H=1 -DHAVE_SSTREAM=1 -DHAVE_TERMIOS_H=1 -DHAVE_TERMIO_H=1 -DHAVE_SGTTY_H=1 -DHAVE_FNMATCH_H=1 -DHAVE_BASENAME=1 -DHAVE_CANONICALIZE_FILE_NAME=1 -DHAVE_CHMOD=1 -DHAVE_DUP2=1 -DHAVE_ENDGRENT=1 -DHAVE_ENDPWENT=1 -DHAVE_EXECVP=1 -DHAVE_EXPM1=1 -DHAVE_EXPM1F=1 -DHAVE_FORK=1 -DHAVE_GETEGID=1 -DHAVE_GETEUID=1 -DHAVE_GETGID=1 -DHAVE_GETGRENT=1 -DHAVE_GETGRGID=1 -DHAVE_GETGRNAM=1 -DHAVE_GETPGRP=1 -DHAVE_GETPID=1 -DHAVE_GETPPID=1 -DHAVE_GETPWENT=1 -DHAVE_GETPWUID=1 -DHAVE_GETUID=1 -DHAVE_GETWD=1 -DHAVE_KILL=1 -DHAVE_LGAMMA=1 -DHAVE_LGAMMAF=1 -DHAVE_LGAMMA_R=1 -DHAVE_LGAMMAF_R=1 -DHAVE_LOCALTIME_R=1 -DHAVE_LOG1P=1 -DHAVE_LOG1PF=1 -DHAVE_MKSTEMP=1 -DHAVE_PIPE=1 -DHAVE_PUTENV=1 -DHAVE_REALPATH=1 -DHAVE_RINDEX=1 -DHAVE_ROUNDL=1 -DHAVE_SELECT=1 -DHAVE_SETGRENT=1 -DHAVE_SETLOCALE=1 -DHAVE_SETPWENT=1 -DHAVE_SETVBUF=1 -DHAVE_SIGLONGJMP=1 -DHAVE_STRSIGNAL=1 -DHAVE_TEMPNAM=1 -DHAVE_TGAMMAF=1 -DHAVE_UMASK=1 -DHAVE_UNAME=1 -DHAVE_UTIME=1 -DHAVE_WAITPID=1 -DHAVE_DECL_EXP2=1 -DHAVE_DECL_ROUND=1 -DHAVE_DECL_TGAMMA=1 -DHAVE_EXP2=1 -DHAVE_ROUND=1 -DHAVE_TGAMMA=1 -DHAVE_DLOPEN_API=1 -DENABLE_DYNAMIC_LINKING=1 -DHAVE_CMATH_ISNAN=1 -DHAVE_CMATH_ISNANF=1 -DHAVE_CMATH_ISINF=1 -DHAVE_CMATH_ISINFF=1 -DHAVE_CMATH_ISFINITE=1 -DHAVE_CMATH_ISFINITEF=1 -DHAVE_FINITE=1 -DHAVE_ISNAN=1 -DHAVE_ISINF=1 -DHAVE_DECL_SIGNBIT=1 -DHAVE_ACOSH=1 -DHAVE_ACOSHF=1 -DHAVE_ASINH=1 -DHAVE_ASINHF=1 -DHAVE_ATANH=1 -DHAVE_ATANHF=1 -DHAVE_ERF=1 -DHAVE_ERFF=1 -DHAVE_ERFC=1 -DHAVE_ERFCF=1 -DHAVE_EXP2F=1 -DHAVE_LOG2=1 -DHAVE_LOG2F=1 -DHAVE_HYPOTF=1 -DHAVE_CBRT=1 -DHAVE_CBRTF=1 -DHAVE_STRUCT_STAT_ST_BLKSIZE=1 -DHAVE_STRUCT_STAT_ST_BLOCKS=1 -DHAVE_STRUCT_STAT_ST_RDEV=1 -DHAVE_STRUCT_TM_TM_ZONE=1 -DHAVE_TM_ZONE=1 -DEXCEPTION_IN_MATH=1 -DHAVE_DECL_SYS_SIGLIST=1 -DHAVE_GETRUSAGE=1 -DYYTEXT_POINTER=1"
#endif

#ifndef OCTAVE_CONF_UMFPACK_CPPFLAGS
#define OCTAVE_CONF_UMFPACK_CPPFLAGS ""
#endif

#ifndef OCTAVE_CONF_UMFPACK_LDFLAGS
#define OCTAVE_CONF_UMFPACK_LDFLAGS ""
#endif

#ifndef OCTAVE_CONF_UMFPACK_LIBS
#define OCTAVE_CONF_UMFPACK_LIBS ""
#endif

#ifndef OCTAVE_CONF_USE_64_BIT_IDX_T
#define OCTAVE_CONF_USE_64_BIT_IDX_T "true"
#endif

#ifndef OCTAVE_CONF_ENABLE_DYNAMIC_LINKING
#define OCTAVE_CONF_ENABLE_DYNAMIC_LINKING "true"
#endif

#ifndef OCTAVE_CONF_X11_INCFLAGS
#define OCTAVE_CONF_X11_INCFLAGS ""
#endif

#ifndef OCTAVE_CONF_X11_LIBS
#define OCTAVE_CONF_X11_LIBS ""
#endif

#ifndef OCTAVE_CONF_XTRA_CFLAGS
#define OCTAVE_CONF_XTRA_CFLAGS ""
#endif

#ifndef OCTAVE_CONF_XTRA_CXXFLAGS
#define OCTAVE_CONF_XTRA_CXXFLAGS ""
#endif

#ifndef OCTAVE_CONF_YACC
#define OCTAVE_CONF_YACC "bison -y"
#endif

#ifndef OCTAVE_CONF_YFLAGS
#define OCTAVE_CONF_YFLAGS ""
#endif

#ifndef OCTAVE_CONF_Z_CPPFLAGS
#define OCTAVE_CONF_Z_CPPFLAGS ""
#endif

#ifndef OCTAVE_CONF_Z_LDFLAGS
#define OCTAVE_CONF_Z_LDFLAGS ""
#endif

#ifndef OCTAVE_CONF_Z_LIBS
#define OCTAVE_CONF_Z_LIBS "-lz"
#endif

#ifndef OCTAVE_CONF_config_opts
#define OCTAVE_CONF_config_opts "'LD_LIBRARY_PATH=/mnt/oqtansTools/oqtans_dep/lib' 'CPPFLAGS=-I/mnt/oqtansTools/oqtans_dep/include' 'LIBS=-L/mnt/oqtansTools/oqtans_dep/lib/' 'LDFLAGS=-L/mnt/oqtansTools/oqtans_dep/lib/' 'F77=gfortran' '--prefix=/mnt/oqtansTools/oqtans_dep/octave-3.4.3' '--with-glpk-includedir=/mnt/oqtansTools/oqtans_dep/include' '--with-glpk-libdir=/mnt/oqtansTools/oqtans_dep/lib' '--with-qhull-includedir=/mnt/oqtansTools/oqtans_dep/include' '--with-qhull-libdir=/mnt/oqtansTools/oqtans_dep/lib' '--with-qrupdate-libdir=/mnt/oqtansTools/oqtans_dep/lib/' '--with-qrupdate-includedir=/mnt/oqtansTools/oqtans_dep/include/' '--without-umfpack' '--disable-readline' '--enable-64'"
#endif

#endif
